#!/usr/bin/env node
/**
 * Supabase → data/menu.json. The reverse of `npm run seed`.
 *
 *   npm run snapshot
 *
 * Two reasons to run it:
 *   1. `getMenu()` falls back to this file whenever Supabase is unreachable,
 *      so a QR scan still returns a menu during an outage. A fresh snapshot
 *      means a fresh fallback.
 *   2. Committing the result gives the owner's edits a plain-text history in
 *      git — a free undo for "what was the couscous price last month?".
 *
 * Reads with the public anon key: this only ever needs the same data a
 * customer can already see.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { createClient } from "@supabase/supabase-js";

const OUT_FILE = path.resolve("data/menu.json");
const ENV_FILE = path.resolve(".env.local");

const c = {
  dim: (s) => `\x1b[2m${s}\x1b[0m`,
  red: (s) => `\x1b[31m${s}\x1b[0m`,
  green: (s) => `\x1b[32m${s}\x1b[0m`,
  bold: (s) => `\x1b[1m${s}\x1b[0m`,
};

const die = (msg) => {
  console.error(`\n${c.red("✗")} ${msg}\n`);
  process.exit(1);
};

async function loadEnvLocal() {
  let raw;
  try {
    raw = await fs.readFile(ENV_FILE, "utf8");
  } catch {
    return;
  }
  for (const line of raw.split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/i);
    if (!m) continue;
    const [, key, value] = m;
    if (!process.env[key]) process.env[key] = value.replace(/^["']|["']$/g, "");
  }
}

await loadEnvLocal();

const URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!URL || !ANON_KEY) {
  die(
    "Missing NEXT_PUBLIC_SUPABASE_URL / NEXT_PUBLIC_SUPABASE_ANON_KEY.\n" +
      "  Fill them in .env.local (Supabase Dashboard → Project Settings → API)."
  );
}

const supabase = createClient(URL, ANON_KEY, {
  auth: { persistSession: false, autoRefreshToken: false },
});

const { data, error } = await supabase.from("categories").select("*, dishes(*)");
if (error) die(`Read failed: ${error.message}`);
if (!data?.length) die("Supabase returned no categories — nothing to snapshot.");

const byPosition = (a, b) => a.position - b.position;

/** Drops null/empty locales so the JSON stays as terse as the hand-written
 * original — `pick()` falls back to fr anyway. */
const localized = (fr, en, ar) => {
  if (!fr?.trim()) return undefined;
  const out = { fr: fr.trim() };
  if (en?.trim()) out.en = en.trim();
  if (ar?.trim()) out.ar = ar.trim();
  return out;
};

const compact = (obj) =>
  Object.fromEntries(Object.entries(obj).filter(([, v]) => v !== undefined));

const categories = data
  .slice()
  .sort(byPosition)
  .map((category) => ({
    id: category.slug,
    title: localized(category.title_fr, category.title_en, category.title_ar),
    ...compact({
      subtitle: localized(
        category.subtitle_fr,
        category.subtitle_en,
        category.subtitle_ar
      ),
    }),
    items: (category.dishes ?? [])
      .filter((dish) => dish.is_available)
      .sort(byPosition)
      .map((dish) =>
        compact({
          id: dish.slug,
          name: localized(dish.name_fr, dish.name_en, dish.name_ar),
          price: dish.price,
          description: localized(
            dish.description_fr,
            dish.description_en,
            dish.description_ar
          ),
          image: dish.image_url ?? undefined,
          width: dish.image_width ?? undefined,
          height: dish.image_height ?? undefined,
        })
      ),
  }));

const output = {
  $comment:
    "Generated by `npm run snapshot` from Supabase. Edits belong in /admin — " +
    "anything written here by hand is overwritten on the next snapshot. Kept " +
    "in git as the offline fallback for getMenu() and as an edit history.",
  categories,
};

await fs.writeFile(OUT_FILE, `${JSON.stringify(output, null, 2)}\n`, "utf8");

const dishCount = categories.reduce((n, cat) => n + cat.items.length, 0);
console.log(
  `\n${c.green("✓")} Wrote ${c.bold("data/menu.json")} — ` +
    `${categories.length} categories, ${dishCount} dishes.\n` +
    c.dim("  Commit it to keep the offline fallback current.\n")
);
